[build]
  # Command to build your project (not applicable for Node.js server)
  command = "echo 'No build steps required'"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[[headers]]
  for = "/server.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"




[[redirects]]
  # Redirect all requests to server.js
  from = "/*"
  to = "/server.js"
  status = 200

[[redirects]]
  # Redirect root requests to server.js
  from = "/"
  to = "/server.js"
  status = 200
